export const FETCH_SAVED_REQUEST = "FETCH_SAVED_REQUEST";
export const FETCH_SAVED_SUCCESS = "FETCH_SAVED_SUCCESS";
export const FETCH_SAVED_FAILURE = "FETCH_SAVED_FAILURE";

export const FETCH_MORE_REQUEST = "FETCH_MORE_REQUEST";
export const FETCH_MORE_SUCCESS = "FETCH_MORE_SUCCESS";
export const FETCH_MORE_FAILURE = "FETCH_MORE_FAILURE";