export const SHOW_ALL_CONTENT = "SHOW_ALL_CONTENT";
export const SHOW_ONLY_COMMENTS = "SHOW_ONLY_COMMENTS"
export const SHOW_ONLY_NSFW = "SHOW_ONLY_NSFW"
export const SHOW_ONLY_SUBREDDIT = "SHOW_ONLY_SUBREDDIT"
export const LOADING_MAIN_VIEW = "LOADING_MAIN_VIEW"